source 'https://rubygems.org'

gem 'berkshelf', '~>3.0'
gem 'test-kitchen'
gem 'kitchen-vagrant'
gem 'foodcritic'
gem 'chefspec'
gem 'strainer', '~>3.3'
gem 'guard'
gem 'guard-foodcritic'
gem 'guard-rspec'
