source 'https://rubygems.org'

gem 'berkshelf'
gem 'test-kitchen'
gem 'busser'
gem 'kitchen-vagrant'
gem 'foodcritic'
gem 'chefspec'
gem 'strainer'
gem 'guard'
gem 'guard-foodcritic'
gem 'guard-rspec'
